spring.application.name=Artificial-Intelligence-Chatbot
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/nlp_chatbot?createDatabaseIfNotExist=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=Port3405@.Af


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.port=8087
